### ISSUE TITLE
this is a bug?

### ISSUE THREAD

**Issue by Phin236** [technisculpt/blender-text-to-speech#1]
just one frame per text
![QQ图片20220510123357](https://user-images.githubusercontent.com/34740477/167543273-37fc9959-f4ea-4c6b-a2fc-4594592fd4a6.png)

**Comment by Phin236** [comment]
![11](https://user-images.githubusercontent.com/34740477/167543524-086faf92-9c4f-49a6-b2dc-71f90b128287.png)

**Comment by technisculpt** [comment]
hi, what operating system are you on and blender version? Can you see any errors in the system console?

**Comment by Phin236** [comment]
![02](https://user-images.githubusercontent.com/34740477/167546179-1bd640d0-ec7a-4b0e-a16f-40bdf96ff0fb.png)
windows 10 and blender 3.1.2

**Comment by Phin236** [comment]
![03](https://user-images.githubusercontent.com/34740477/167546306-ebe2936c-3684-4b84-ad84-06bc5dfc54ca.png)

**Comment by technisculpt** [comment]
did you install blender from steam? I will try to do that and see if i can recreate

**Comment by Phin236** [comment]
yes steam

**Comment by technisculpt** [comment]
what is your output path set to in  "output properties"
try changing it to be on the same hard drive as your blender install (D:)

**Comment by Phin236** [comment]
![image](https://user-images.githubusercontent.com/34740477/167552251-f8082d23-110b-4d36-9f23-a85597d0cb1f.png)

**Comment by Phin236** [comment]
do you mean this output prop?

**Comment by technisculpt** [comment]
yes it shouldn't have forward slashes on windows, it should have backslashes for example: D:\test\

**Comment by Phin236** [comment]
awesome  its worked now!!

**Comment by technisculpt** [comment]
awesome :)

**Comment by Phin236** [comment]
But my blender projects are all paths using this double slash ...
Can your plugin be changed to support this path format?

**Comment by technisculpt** [comment]
even if you select the path from Blender they have a double slash?

**Comment by technisculpt** [comment]
can you try replacing the double slash with a single slash?

**Comment by technisculpt** [comment]
ok i understand the problem now, the double slash is blenders convention for a relative path. I just pushed a change, it should work for you now
