### ISSUE TITLE
Add-on not installed

### ISSUE THREAD

**Issue by xtech-2020** [technisculpt/blender-text-to-speech#2]
Hi, I'm trying to install the add-on via preferences, but I can't, 
- I'm in administrator mode,
- I'm using Blender 3.1.2, in Windows 10

Every time I get the following message: "_Modules Installed () from '....zip' into '...'_"

Am I doing something wrong?

**Comment by technisculpt** [comment]
you might be installing the github repo. You need to unzip the repo, zip the folder entitled "Text to Speech" and install that

**Comment by xtech-2020** [comment]
Thank you very much, it works perfectly.

One more question, please: How can I make it recognize some voices I have installed from Vocalizer (taken from nuance.com)? At the moment it only works with the ones that come with the operating system by default.

**Comment by technisculpt** [comment]
sorry i am not affiliated with nuance, this addon only supports the OS defaults

**Comment by xtech-2020** [comment]
Ok, Thanks 👍
