### ISSUE TITLE
Addon doesn't seem add any  menu option (What Blender version is used? and how to fix?)

### ISSUE THREAD

**Issue by iGodCollective** [technisculpt/blender-text-to-speech#5]
My screen, blender 2.92.0

Not seeing the menu option after plugin is installed. 

![image](https://github.com/technisculpt/blender-text-to-speech/assets/161035122/a972722b-9aa9-49a8-8fb1-2f369389270f)

**Comment by iGodCollective** [comment]
I saw that in the video you used 3.1.0. So I'll try that and report.

**Comment by technisculpt** [comment]
It gets added to the sequence editor. Try opening with the default set up for video editor. It should work in version 2.x

**Comment by iGodCollective** [comment]
> It gets added to the sequence editor. Try opening with the default set up for video editor. It should work in version 2.x

Thanks.

It's interesting that I made a whole [open source Ai plugin for blender](https://github.com/g0dEngineer/Cryptosynth), and I saw SEQUENCE_EDITOR > UI > Text to Speech in addon desc, and didn't bother checking for that

**Comment by iGodCollective** [comment]
> It gets added to the sequence editor. Try opening with the default set up for video editor. It should work in version 2.x

Okay, tried it in 2.91, found the drop down.
When I enter text and hit "text to speech" it reports an "output path doesn't exist" error.
Will dig down to find out the issue. 

![image](https://github.com/technisculpt/blender-text-to-speech/assets/161035122/98005bbe-c2c2-4608-b4b2-952b6669291b)

**Comment by technisculpt** [comment]
Can you screen shot the full error please?

**Comment by technisculpt** [comment]
Oh what have you set as your render path?

**Comment by iGodCollective** [comment]
> Oh what have you set as your render path?

That wasn't set at all!!

**Comment by iGodCollective** [comment]
> Can you screen shot the full error please?

Thanks.
It's the full error, "Output path doesn't exist"

> Oh what have you set as your render path?

Nothing was there, thanks. I set that path with your advice, but still same error. Still digging down.

**Comment by technisculpt** [comment]
Do you get any further information in the console?

**Comment by iGodCollective** [comment]
> Do you get any further information in the console?

Thanks for reply again.
After setting the Sound path, a new error associated with [text_to_sound.py](https://github.com/technisculpt/blender-text-to-speech/blob/main/Text%20to%20Speech/text_to_sound.py), [caption.py](https://github.com/technisculpt/blender-text-to-speech/blob/main/Text%20to%20Speech/caption.py), and eventually [operators.py](https://github.com/technisculpt/blender-text-to-speech/blob/main/Text%20to%20Speech/operators.py) emerged:


![image](https://github.com/technisculpt/blender-text-to-speech/assets/161035122/17ee7f3f-b08e-46a0-852f-7a2779e50102)

**Comment by iGodCollective** [comment]
> Do you get any further information in the console?

I fixed the error

**Comment by iGodCollective** [comment]
> Do you get any further information in the console?

In text_to_sound.py:

From imports: After swapping out "from sys import platform" with "import sys as system" 
From sound_strip_from_text func: After swapping out {if sys.platform == "darwin"} with " {if system.platform == "darwin"} 

The tool generated the audio successfully

![image](https://github.com/technisculpt/blender-text-to-speech/assets/161035122/7de9072f-bac9-49dc-b983-68d77912f876)

**Comment by technisculpt** [comment]
Nice one do you want to do a pull request?

**Comment by technisculpt** [comment]
ok, this is my bad.
in my last commit, I removed "import sys" erroneously, I saw "from sys import platform". When i start a project I import the entire package then eventually i refactor to only import the modules used. However I missed that i was still calling "sys.platform" instead of just "platform"... i.e i started to refactor and didn't finish or something, dumb and naughty to commit breaking changes without testing & without automated tests a lesson to not do that even if it seems trivial...

so i'm sorry and thankyou for bringing it to my attention. reverting back a commit until i have time to test

**Comment by iGodCollective** [comment]
> ok, this is my bad. in my last commit, I removed "import sys" erroneously, I saw "from sys import platform". When i start a project I import the entire package then eventually i refactor to only import the modules used. However I missed that i was still calling "sys.platform" instead of just "platform"... i.e i started to refactor and didn't finish or something, dumb and naughty to commit breaking changes without testing & without automated tests a lesson to not do that even if it seems trivial...
> 
> so i'm sorry and thankyou for bringing it to my attention. reverting back a commit until i have time to test

No worries bro, we're all human for now, we make little miniscule errors from time to time

Thanks for guiding me along the way, and thanks for this beautiful project

**Comment by technisculpt** [comment]
thanks for the kind words. looking forward to checking out your a.i addon :)

**Comment by iGodCollective** [comment]
> thanks for the kind words. looking forward to checking out your a.i addon :)

Cool. Thanks!!!

1. Right now, [the blender/scene and addon seen here](https://github.com/g0dEngineer/Cryptosynth), integrates gpt2 conversational/llm unit to enable a **_text response_** associated with the 3d Aeon being.

2. The being is a 3d model generated by ai, currently little expressions, she just moves her eyes to act like she's reading user input before **_text response._**

3.With your project I will add a voice to the being, beyond text response. After that I will rig the being to be able to have emotions or.

So I will just play the generated sound that your project produces, based on the text response.

`
What's good about the ai is that it runs locally, with no need for any api key, since it's a pretrained model/weight unit.`

**Comment by technisculpt** [comment]
sounds like a lot of fun and something I would be interested in contributing to if i wasn't so busy.

You should follow @tin2tin. He made a blender addon for screenplay writing and helped me out with text-to-speech. But he is prolific in researching open source a.i projects and my github feed is constantly filled with a tonne of really interesting repos that he has recently starred mostly to do with LLMs, text to voice, voice to text, text to image, text to mesh object, text to video etc etc. Really good guy to follow.

**Comment by g0dEngineer** [comment]
> oh i didn't even realize he has made this huge addon called [Paladium](https://github.com/tin2tin/Pallaidium) which is insane and very much up your alley. I must play with this.

Thanks.

I ended up using pyttsx3 for the text to speech, as it was compatible with my version of blender, combined with Rhubarb LipSync Plugin for lipsyncing, though the lip-syncing could use some refinement.

Albeit it works and my synth finally moves her mouth and speaks words via Ai:

![image](https://github.com/g0dEngineer/AURA_AEON_HUMAN/blob/main/screenshots/aura_human_face_rig_eye_movement_movie__annotated.gif)

~Paladium seems very intriguing. I will find a way to integrate that too, or just introduce that to students.
